module.exports = [
  'Virtual Cloud Network',
  'Telemetry',
  'API Gateway',
  'Container Engine for Kubernetes',
  'Object Storage',
  'Compute',
  'Load Balancer',
  'Logging',
  'Data Science',
  'Content Management',
  'Analytics',
  'Database',
  'Virtual Private Network',
  'MySQL',
  'DNS',
  'Key Management',
  'Notifications',
  'Data Flow',
  'File Storage',
  'Functions',
  'Health Checks',
  'Data Integration',
  'Block Storage',
  'Application Performance Monitoring',
  'Database Management',
  'Full Stack Disaster Recovery Service',
  'GoldenGate',
  'Logging Analytics',
  'Email Delivery',
  'Content and Experience',
  'Centralized Repository for Threat Intelligence Data',
  'Content Management - DEV',
  ' ',
  'Edge Services',
  'Oracle Web Application Firewall (WAF)',
  'Integration Service',
  'NoSQL Database'
];